Repository codesquad-members-2021/baseball, pull requests merged in 2021-05, with the labels that each got.

#5 [ FE ][Team 15: Yeon, Beemo, Jenny] 전반적인 뷰 틀 구성 완료
  BE/.gitignore
  FE/.gitignore
  FE/client/README.md
  FE/client/jsconfig.json
  FE/client/package.json
  FE/client/public/index.html
  FE/client/src/App.js
  FE/client/src/Components/GamePage/GamePageHeader/HeaderLeft/BaseballHeaderScore.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderLeft/index.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderRight/CurrentPlayer.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderRight/index.jsx
  FE/client/src/Components/GamePage/GamePageHeader/index.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/AttackDefendStatus.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/BaseballField.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/BaseballMonitor.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/PitchButton.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/RunnerImage.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/SBOStatus.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/index.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoard.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoardItems.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoardList.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/index.jsx
  FE/client/src/Components/GamePage/MainContainer/index.jsx
  FE/client/src/Components/GamePage/Popup/BottomPopup.jsx
  FE/client/src/Components/GamePage/Popup/GameScoreTable.jsx
  FE/client/src/Components/GamePage/Popup/PlayerScoreTable.jsx
  FE/client/src/Components/GamePage/Popup/TopPopup.jsx
  FE/client/src/Components/GamePage/Popup/index.jsx
  FE/client/src/Components/GamePage/index.jsx
  FE/client/src/Components/Home/AvailableGameSpan/index.jsx
  FE/client/src/Components/Home/GameList/Game.jsx
  FE/client/src/Components/Home/GameList/Team.jsx
  FE/client/src/Components/Home/GameList/index.jsx
  FE/client/src/Components/Home/index.jsx
  FE/client/src/Components/Page/index.jsx
  FE/client/src/Images/Background.jpg
  FE/client/src/Images/arms.svg
  FE/client/src/Images/bodyAndHead.svg
  FE/client/src/Images/foot.svg
  FE/client/src/Images/pants.svg
  FE/client/src/index.js
  FE/client/src/utils/canvasUtils.js
  FE/client/src/utils/hooks/useTogglePopup.js
  FE/client/src/utils/mockDatas.js
Labels: review-FE

#3 [ Team-17 / Ah-puh / FE ] View & Oauth 구현
  .github/workflows/test-api-server.yml
  .gitignore
  BE/init
  FE/.gitignore
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/image/base.png
  FE/public/image/base2.png
  FE/public/image/batter.png
  FE/public/image/mlbground_edit.jpg
  FE/public/image/pitcher.png
  FE/public/image/pitcher_eagles.png
  FE/public/image/pitcher_eagles_heart.png
  FE/public/image/runner_running.png
  FE/public/image/runner_waiting.png
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.js
  FE/src/App.test.js
  FE/src/GlobalStyle.jsx
  FE/src/components/Home/Home.jsx
  FE/src/components/InGame/Ground/BallCount.jsx
  FE/src/components/InGame/Ground/Ground.jsx
  FE/src/components/InGame/Ground/Header.jsx
  FE/src/components/InGame/Ground/Main.jsx
  FE/src/components/InGame/InGame.jsx
  FE/src/components/InGame/LineUp/LineUp.jsx
  FE/src/components/InGame/LineUp/Table.jsx
  FE/src/components/InGame/Record/Bottom.jsx
  FE/src/components/InGame/Record/Record.jsx
  FE/src/components/InGame/Record/RecordOfPlayer.jsx
  FE/src/components/InGame/Record/Top.jsx
  FE/src/components/InGame/ScoreBoard/ScoreBoard.jsx
  FE/src/components/InGame/ScoreBoard/Table.jsx
  FE/src/components/Intro/Game.jsx
  FE/src/components/Intro/Intro.jsx
  FE/src/components/Intro/TeamSelect.jsx
  FE/src/components/NoMatch/NoMatch.jsx
  FE/src/config/authMethods.js
  FE/src/config/firebase-config.js
  FE/src/env.css
  FE/src/index.js
  FE/src/reportWebVitals.js
  FE/src/service/auth.js
  FE/src/setupTests.js
  FE/src/utils/getRandomPitchResult/getRandomPitchResult.js
  FE/src/utils/getRandomPitchResult/test.js
Labels: review-FE

#4 [FE][Json,Kyle] 야구게임 UI 1차 구현
  README.md
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/src/App.css
  fe/src/App.js
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/BallCount.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Inning.jsx
  fe/src/components/game-play/board/Screen.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/components/game-play/popup/roster/Roster.jsx
  fe/src/components/game-play/popup/roster/TeamRoster.jsx
  fe/src/components/game-play/popup/score/Score.jsx
  fe/src/components/game-play/popup/score/ScoreList.jsx
  fe/src/components/game-play/score/Score.jsx
  fe/src/components/ui/PopUp.jsx
  fe/src/images/background.png
  fe/src/index.css
  fe/src/index.js
Labels: review-FE

#2 [Team09 - 쑤 & 쏭] Layout 및 Model 구현
  .gitignore
  iOS/BaseballApp/BaseballApp.xcodeproj/project.pbxproj
  iOS/BaseballApp/BaseballApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/BaseballApp/BaseballApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/BaseballApp/BaseballApp/Controllers/LobbyViewController.swift
  iOS/BaseballApp/BaseballApp/Controllers/PlayViewController.swift
  iOS/BaseballApp/BaseballApp/Entity/Game.swift
  iOS/BaseballApp/BaseballApp/Entity/Room.swift
  iOS/BaseballApp/BaseballApp/Info.plist
  iOS/BaseballApp/BaseballApp/Network/APIRequestManager.swift
  iOS/BaseballApp/BaseballApp/Supporting Files/AppDelegate.swift
  iOS/BaseballApp/BaseballApp/Supporting Files/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/BaseballApp/BaseballApp/Supporting Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/BaseballApp/BaseballApp/Supporting Files/Assets.xcassets/Contents.json
  iOS/BaseballApp/BaseballApp/Supporting Files/Base.lproj/LaunchScreen.storyboard
  iOS/BaseballApp/BaseballApp/Supporting Files/SceneDelegate.swift
  iOS/BaseballApp/BaseballApp/UIView+Identifier.swift
  iOS/BaseballApp/BaseballApp/UseCases/GameUseCase.swift
  iOS/BaseballApp/BaseballApp/UseCases/RoomsUseCase.swift
  iOS/BaseballApp/BaseballApp/ViewModel/GameViewModel.swift
  iOS/BaseballApp/BaseballApp/ViewModel/RoomsViewModel.swift
  iOS/BaseballApp/BaseballApp/Views/Base.lproj/Main.storyboard
  iOS/BaseballApp/BaseballApp/Views/CountView.swift
  iOS/BaseballApp/BaseballApp/Views/CurrentPlayerView.swift
  iOS/BaseballApp/BaseballApp/Views/CurrentPlayerView.xib
  iOS/BaseballApp/BaseballApp/Views/GroundView.swift
  iOS/BaseballApp/BaseballApp/Views/GroundView.xib
  iOS/BaseballApp/BaseballApp/Views/PitcherRecordTableViewCell.swift
  iOS/BaseballApp/BaseballApp/Views/PitcherRecordTableViewCell.xib
  iOS/BaseballApp/BaseballApp/Views/RoomTableViewCell.swift
  iOS/BaseballApp/BaseballApp/Views/ScoreHeaderView.swift
  iOS/BaseballApp/BaseballApp/Views/ScoreHeaderView.xib
  iOS/BaseballApp/BaseballAppTests/BaseballAppTests.swift
  iOS/BaseballApp/BaseballAppTests/Info.plist
  iOS/BaseballApp/BaseballAppUITests/BaseballAppUITests.swift
  iOS/BaseballApp/BaseballAppUITests/Info.plist
Labels: review-iOS

#18 [Team11/adela, eve] 간단한 pitch 동작 구현
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/src/App.css
  fe/src/App.jsx
  fe/src/App.test.js
  fe/src/components/game/CurrentPlayer.jsx
  fe/src/components/game/DetailScorePopup.jsx
  fe/src/components/game/Game.jsx
  fe/src/components/game/PlayerHistory.jsx
  fe/src/components/game/PlayerListPopup.jsx
  fe/src/components/game/TeamScore.jsx
  fe/src/components/game/baseballField/CurrentInningInfo.jsx
  fe/src/components/game/baseballField/Diamond.jsx
  fe/src/components/game/baseballField/PitchButton.jsx
  fe/src/components/game/baseballField/SBO.jsx
  fe/src/components/main/Main.jsx
  fe/src/components/main/Message.jsx
  fe/src/components/main/Teams.jsx
  fe/src/components/shared/Title.jsx
  fe/src/index.css
  fe/src/index.js
  fe/src/reset.css
Labels: review-FE

#19 [Team14 / Daisy ppamppam] FE PR
  README.md
  backend/README.md
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/assets/mock_data/CurrentPlayer.json
  fe/public/assets/mock_data/Game.json
  fe/public/assets/mock_data/PlayerList.json
  fe/public/assets/mock_data/Score.json
  fe/public/index.html
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.js
  fe/src/components/CurrentPlayerSection/CurrentPlayer.js
  fe/src/components/GameOrigin/GameList.jsx
  fe/src/components/GameOrigin/GameListItem.jsx
  fe/src/components/HistorySection/HistoryCard.js
  fe/src/components/HistorySection/HistoryList.js
  fe/src/components/PlaySection/PlayField.jsx
  fe/src/components/PlaySection/PlayFieldCanvas.jsx
  fe/src/components/PlaySection/PlayInning.jsx
  fe/src/components/PlaySection/PlayPitch.jsx
  fe/src/components/PlaySection/PlaySBOInfo.jsx
  fe/src/components/PlaySection/PlaySection.jsx
  fe/src/components/ScoreBoard/ScoreBoard.jsx
  fe/src/components/common/GameCard.jsx
  fe/src/components/common/GameList.jsx
  fe/src/components/common/GameMessage.jsx
  fe/src/components/common/Responsive.jsx
  fe/src/index.css
  fe/src/index.js
  fe/src/pages/HomePage.jsx
  fe/src/pages/MainPage.jsx
  fe/src/util/API.js
  fe/src/util/hooks/useFetch.js
  fe/src/util/hooks/useGameSelect.jsx
Labels: review-FE

#30 [ FE ][Team 15: Yeon, Beemo, Jenny] GamePage 진행중.. (소켓 사용중)
  FE/client/jsconfig.json
  FE/client/package.json
  FE/client/public/index.html
  FE/client/server/server.js
  FE/client/src/App.js
  FE/client/src/Components/GamePage/GamePageHeader/HeaderLeft/BaseballHeaderScore.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderLeft/index.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderRight/CurrentPlayer.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderRight/index.jsx
  FE/client/src/Components/GamePage/GamePageHeader/index.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/AttackDefendStatus.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/BaseballField.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/PitchButton.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/RunnerImage.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/SBOStatus.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/index.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoard.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoardItems.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoardList.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/index.jsx
  FE/client/src/Components/GamePage/MainContainer/index.jsx
  FE/client/src/Components/GamePage/Popup/BottomPopup.jsx
  FE/client/src/Components/GamePage/Popup/GameScoreTable.jsx
  FE/client/src/Components/GamePage/Popup/PlayerScoreTable.jsx
  FE/client/src/Components/GamePage/Popup/TopPopup.jsx
  FE/client/src/Components/GamePage/Popup/index.jsx
  FE/client/src/Components/GamePage/index.jsx
  FE/client/src/Components/Home/GameList/Game.jsx
  FE/client/src/Components/Home/GameList/Team.jsx
  FE/client/src/Components/Home/GameList/index.jsx
  FE/client/src/Components/Home/index.jsx
  FE/client/src/Components/Page/index.jsx
  FE/client/src/Images/arms.svg
  FE/client/src/Images/bodyAndHead.svg
  FE/client/src/Images/foot.svg
  FE/client/src/Images/pants.svg
  FE/client/src/Images/readyPlayer.svg
  FE/client/src/index.js
  FE/client/src/utils/API.js
  FE/client/src/utils/BeemoRouter.jsx
  FE/client/src/utils/canvasUtils.js
  FE/client/src/utils/hooks/useAsync.js
Labels: review-FE

#21 [Team 08][Cri, Dumba] View 화면 구성및 네트워크 연동
  .gitignore
  Baseball/Baseball.xcodeproj/project.pbxproj
  Baseball/Baseball.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Baseball/Baseball.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Baseball/Baseball/Application/AppDelegate.swift
  Baseball/Baseball/Application/AppFlowCoordinator.swift
  Baseball/Baseball/Application/DIContainer/AppDIContainer.swift
  Baseball/Baseball/Application/DIContainer/BaseballSceneDIContainer.swift
  Baseball/Baseball/Application/SceneDelegate.swift
  Baseball/Baseball/Data/Network/DataMapping/GameListDTO+Mapping.swift
  Baseball/Baseball/Data/Network/NetworkEndpoint.swift
  Baseball/Baseball/Data/Network/NetworkService.swift
  Baseball/Baseball/Data/Repository/GameListRepository.swift
  Baseball/Baseball/Domain/Entity/MatchUp.swift
  Baseball/Baseball/Domain/UseCase/FetchGameListUseCase.swift
  Baseball/Baseball/Presentation/Common/CALayer+Extension.swift
  Baseball/Baseball/Presentation/Common/GameScoreHeader.xib
  Baseball/Baseball/Presentation/Common/PaddingLabel.swift
  Baseball/Baseball/Presentation/Flow/BaseballSceneFlowCoordinator.swift
  Baseball/Baseball/Presentation/GameListView/View/GameListCell.swift
  Baseball/Baseball/Presentation/GameListView/View/GameListViewController.swift
  Baseball/Baseball/Presentation/GameListView/ViewModel/GameListViewModel.swift
  Baseball/Baseball/Presentation/GamePlayView/View/GamePlayViewController.swift
  Baseball/Baseball/Presentation/GamePlayView/View/GroundView.swift
  Baseball/Baseball/Presentation/GamePlayView/View/PitchHistoryCell.swift
  Baseball/Baseball/Presentation/GamePlayView/View/PitchHistoryView.swift
  Baseball/Baseball/Presentation/Utils/Alertable.swift
  Baseball/Baseball/SupportingFile/Assets.xcassets/AccentColor.colorset/Contents.json
  Baseball/Baseball/SupportingFile/Assets.xcassets/AppIcon.appiconset/Contents.json
  Baseball/Baseball/SupportingFile/Assets.xcassets/Contents.json
  Baseball/Baseball/SupportingFile/Base.lproj/LaunchScreen.storyboard
  Baseball/Baseball/SupportingFile/Base.lproj/Main.storyboard
  Baseball/Baseball/SupportingFile/Info.plist
Labels: review-iOS

#7 [Team06 - 롤로 & 리아] (로그인 & 게임 선택 & 게임 진행) 화면 + mock api 테스트
  BE/README.md
  DOCS/README.md
  iOS/.gitignore
  iOS/README.md
  iOS/baseball-game/baseball-game.xcodeproj/project.pbxproj
  iOS/baseball-game/baseball-game.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/baseball-game/baseball-game.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/baseball-game/baseball-game.xcodeproj/project.xcworkspace/xcuserdata/song.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/baseball-game/baseball-game.xcodeproj/xcshareddata/xcschemes/baseball-game.xcscheme
  iOS/baseball-game/baseball-game.xcodeproj/xcuserdata/song.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/baseball-game/baseball-game/AppCycle/AppDelegate.swift
  iOS/baseball-game/baseball-game/AppCycle/SceneDelegate.swift
  iOS/baseball-game/baseball-game/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Contents.json
  iOS/baseball-game/baseball-game/Base.lproj/LaunchScreen.storyboard
  iOS/baseball-game/baseball-game/Base.lproj/Main.storyboard
  iOS/baseball-game/baseball-game/ControllerFactory.swift
  iOS/baseball-game/baseball-game/GamePlay/GamePlayViewController.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/GameManagable.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/GameManager.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Pitch.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Player.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Turn.swift
  iOS/baseball-game/baseball-game/GamePlay/SelectPitcher/SelectPitcherViewController.swift
  iOS/baseball-game/baseball-game/GamePlay/View/BatterInfoView.swift
  iOS/baseball-game/baseball-game/GamePlay/View/GamePlay.storyboard
  iOS/baseball-game/baseball-game/GamePlay/View/PitchListTableViewCell.swift
  iOS/baseball-game/baseball-game/GamePlay/View/PitcherInfoView.swift
  iOS/baseball-game/baseball-game/GamePlay/View/TeamScoreView.swift
  iOS/baseball-game/baseball-game/GamePlay/ViewModel/GamePlayViewModel.swift
  iOS/baseball-game/baseball-game/IdentifierReusable.swift
  iOS/baseball-game/baseball-game/Info.plist
  iOS/baseball-game/baseball-game/Network/Network.swift
  iOS/baseball-game/baseball-game/Selection/LoginViewController.swift
  iOS/baseball-game/baseball-game/Selection/Model/Game.swift
  iOS/baseball-game/baseball-game/Selection/Model/GameInfo.swift
  iOS/baseball-game/baseball-game/Selection/Model/Team.swift
  iOS/baseball-game/baseball-game/Selection/SelectionViewController.swift
  iOS/baseball-game/baseball-game/Selection/View/GameCell.swift
  iOS/baseball-game/baseball-game/Selection/View/GameCell.xib
  iOS/baseball-game/baseball-game/Selection/ViewModel/SelectViewModel.swift
Labels: review-iOS

#36 [iOS Team-08][Cri, Dumba]
  Baseball/Baseball.xcodeproj/project.pbxproj
  Baseball/Baseball/Application/DIContainer/BaseballSceneDIContainer.swift
  Baseball/Baseball/Application/SceneDelegate.swift
  Baseball/Baseball/Data/Network/DataMapping/GameListDTO+Mapping.swift
  Baseball/Baseball/Data/Network/DataMapping/GamePlayDTO+Mapping.swift
  Baseball/Baseball/Data/Network/DataMapping/PlayerRecordDTO+Mapping.swift
  Baseball/Baseball/Data/Network/NetworkEndpoint.swift
  Baseball/Baseball/Data/Network/NetworkService.swift
  Baseball/Baseball/Data/Repository/GameListRepository.swift
  Baseball/Baseball/Data/Repository/GamePlayRepository.swift
  Baseball/Baseball/Data/Repository/PlayerRecordRepository.swift
  Baseball/Baseball/Domain/Entity/GamePlay.swift
  Baseball/Baseball/Domain/Entity/PlayerRecord.swift
  Baseball/Baseball/Domain/UseCase/FetchGameListUseCase.swift
  Baseball/Baseball/Domain/UseCase/FetchGamePlayUseCase.swift
  Baseball/Baseball/Domain/UseCase/FetchPlayerRecordsUseCase.swift
  Baseball/Baseball/Presentation/Common/GameScoreHeader.xib
  Baseball/Baseball/Presentation/Flow/BaseballSceneFlowCoordinator.swift
  Baseball/Baseball/Presentation/GameListView/View/GameListViewController.swift
  Baseball/Baseball/Presentation/GameListView/ViewModel/GameListViewModel.swift
  Baseball/Baseball/Presentation/GamePlayView/View/GamePlayViewController.swift
  Baseball/Baseball/Presentation/GamePlayView/ViewModel/GamePlayViewModel.swift
  Baseball/Baseball/Presentation/GameScoreView/View/GameScoreTableViewCell.swift
  Baseball/Baseball/Presentation/GameScoreView/View/GameScoreViewController.swift
  Baseball/Baseball/Presentation/GameScoreView/View/RecordsTableViewHeader.swift
  Baseball/Baseball/Presentation/GameScoreView/View/RecordsTableViewHeader.xib
  Baseball/Baseball/Presentation/TabBar/InGameTabBarController.swift
  Baseball/Baseball/Presentation/Utils/GameScoreViewModel.swift
  Baseball/Baseball/Presentation/Utils/RunnerView.swift
  Baseball/Baseball/SupportingFile/Assets.xcassets/analytics.imageset/Contents.json
  Baseball/Baseball/SupportingFile/Assets.xcassets/analytics.imageset/analytics.png
  Baseball/Baseball/SupportingFile/Assets.xcassets/baseball-player.imageset/Contents.json
  Baseball/Baseball/SupportingFile/Assets.xcassets/baseball-player.imageset/baseball-player.png
  Baseball/Baseball/SupportingFile/Base.lproj/Main.storyboard
Labels: review-iOS

#20 [Team05 - Re Pull Request]
  README.md
  c.mov
  iOS/.gitignore
  iOS/baseballApp/Podfile
  iOS/baseballApp/Podfile.lock
  iOS/baseballApp/baseballApp.xcodeproj/project.pbxproj
  iOS/baseballApp/baseballApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/baseballApp/baseballApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/baseballApp/baseballApp.xcworkspace/contents.xcworkspacedata
  iOS/baseballApp/baseballApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/baseballApp/baseballApp/AppDelegate.swift
  iOS/baseballApp/baseballApp/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/baseballApp/baseballApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/baseballApp/baseballApp/Assets.xcassets/Contents.json
  iOS/baseballApp/baseballApp/Assets.xcassets/background.imageset/Contents.json
  iOS/baseballApp/baseballApp/Assets.xcassets/background.imageset/background.jpg
  iOS/baseballApp/baseballApp/Assets.xcassets/background.jpg
  iOS/baseballApp/baseballApp/Assets.xcassets/baseball_player.imageset/Contents.json
  iOS/baseballApp/baseballApp/Assets.xcassets/baseball_player.imageset/baseball_player-2.png
  iOS/baseballApp/baseballApp/Assets.xcassets/score.imageset/Contents.json
  iOS/baseballApp/baseballApp/Assets.xcassets/score.imageset/score.png
  iOS/baseballApp/baseballApp/Assets.xcassets/score.png
  iOS/baseballApp/baseballApp/Base.lproj/LaunchScreen.storyboard
  iOS/baseballApp/baseballApp/Constant.swift
  iOS/baseballApp/baseballApp/Data/Network/APIService.swift
  iOS/baseballApp/baseballApp/Data/Network/DataMapping/GameDTO.swift
  iOS/baseballApp/baseballApp/Data/Network/DataMapping/PlayDTO.swift
  iOS/baseballApp/baseballApp/Data/Network/DataMapping/ScoreDTO.swift
  iOS/baseballApp/baseballApp/Data/Network/Endpoint.swift
  iOS/baseballApp/baseballApp/Domain/Entity/BallCount.swift
  iOS/baseballApp/baseballApp/Domain/Entity/Game.swift
  iOS/baseballApp/baseballApp/Domain/Entity/PlayInfo.swift
  iOS/baseballApp/baseballApp/Domain/Entity/Player.swift
  iOS/baseballApp/baseballApp/Domain/Entity/Record.swift
  iOS/baseballApp/baseballApp/Info.plist
  iOS/baseballApp/baseballApp/Presentation/UI/Storyboard/Base.lproj/Main.storyboard
  iOS/baseballApp/baseballApp/Presentation/UI/Storyboard/PlayStoryboard.storyboard
  iOS/baseballApp/baseballApp/Presentation/UI/Storyboard/ScoreStoryboard.storyboard
  iOS/baseballApp/baseballApp/Presentation/UI/View/BallCountView.swift
  iOS/baseballApp/baseballApp/Presentation/UI/View/BallListCell.swift
  iOS/baseballApp/baseballApp/Presentation/UI/View/BallListCell.xib
  iOS/baseballApp/baseballApp/Presentation/UI/View/GameCell.swift
  iOS/baseballApp/baseballApp/Presentation/UI/View/ScoreCell.swift
  iOS/baseballApp/baseballApp/Presentation/UI/View/StadiumView.swift
  iOS/baseballApp/baseballApp/Presentation/UI/ViewController/HomeViewController.swift
  iOS/baseballApp/baseballApp/Presentation/UI/ViewController/PlayViewController.swift
  iOS/baseballApp/baseballApp/Presentation/UI/ViewController/ScoreViewController.swift
  iOS/baseballApp/baseballApp/Presentation/ViewModel/GameViewModel.swift
  iOS/baseballApp/baseballApp/Presentation/ViewModel/GameViewModelType.swift
  iOS/baseballApp/baseballApp/Presentation/ViewModel/PlayViewModel.swift
  iOS/baseballApp/baseballApp/Presentation/ViewModel/ScoreViewModel.swift
  iOS/baseballApp/baseballApp/SceneDelegate.swift
  iOS/baseballApp/baseballAppTests/Info.plist
  iOS/baseballApp/baseballAppTests/baseballAppTests.swift
  iOS/baseballApp/baseballAppUITests/Info.plist
  iOS/baseballApp/baseballAppUITests/baseballAppUITests.swift
Labels: review-iOS

#22 [BE][Team-15, yeon] baseball 기능 구현과 배포
  .gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/baseball/BaseballApplication.java
  BE/src/main/java/baseball/CorsFilter.java
  BE/src/main/java/baseball/controller/GameController.java
  BE/src/main/java/baseball/controller/GlobalExceptionHandler.java
  BE/src/main/java/baseball/controller/TeamController.java
  BE/src/main/java/baseball/domain/Game.java
  BE/src/main/java/baseball/domain/Member.java
  BE/src/main/java/baseball/domain/Record.java
  BE/src/main/java/baseball/domain/Score.java
  BE/src/main/java/baseball/domain/Team.java
  BE/src/main/java/baseball/exception/GameNotFoundException.java
  BE/src/main/java/baseball/exception/MemberNotFoundException.java
  BE/src/main/java/baseball/exception/NotFoundException.java
  BE/src/main/java/baseball/exception/TeamNotFoundException.java
  BE/src/main/java/baseball/repository/GameRepository.java
  BE/src/main/java/baseball/repository/TeamRepository.java
  BE/src/main/java/baseball/service/GameService.java
  BE/src/main/java/baseball/service/TeamService.java
  BE/src/main/java/baseball/service/dto/GameDTO.java
  BE/src/main/java/baseball/service/dto/GameScoreDTO.java
  BE/src/main/java/baseball/service/dto/GameTeamDTO.java
  BE/src/main/java/baseball/service/dto/Games.java
  BE/src/main/java/baseball/service/dto/MemberDTO.java
  BE/src/main/java/baseball/service/dto/RecordDTO.java
  BE/src/main/java/baseball/service/dto/RecordRequest.java
  BE/src/main/java/baseball/service/dto/ScoreRequest.java
  BE/src/main/java/baseball/service/dto/TeamDTO.java
  BE/src/main/java/baseball/service/dto/TeamRequest.java
  BE/src/main/java/baseball/service/dto/TeamScoreDTO.java
  BE/src/main/java/baseball/service/dto/TeamsDTO.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
Labels: review-BE

#37 [Team06 - 롤로 & 리아] 수비 턴 게임 진행 & 경기 그래픽 + 애니메이션
  iOS/baseball-game/baseball-game.xcodeproj/project.pbxproj
  iOS/baseball-game/baseball-game.xcodeproj/project.xcworkspace/xcuserdata/song.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/Back.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/Ball.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/CounterBorder.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/Out.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/Strike.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/BallCounter/Text.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/Base.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/BaseSelected.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/GroundBorder.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/GroundBrown.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/GroundGreen.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Ground/Home.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Player/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Player/PlayerBody.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Player/PlayerBorder.colorset/Contents.json
  iOS/baseball-game/baseball-game/Assets.xcassets/Player/PlayerFace.colorset/Contents.json
  iOS/baseball-game/baseball-game/GamePlay/GamePlayViewController.swift
  iOS/baseball-game/baseball-game/GamePlay/GroundGraphics/BallCountView.swift
  iOS/baseball-game/baseball-game/GamePlay/GroundGraphics/Collection + subscript.swift
  iOS/baseball-game/baseball-game/GamePlay/GroundGraphics/GroundView.swift
  iOS/baseball-game/baseball-game/GamePlay/GroundGraphics/PlayerLayer.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/BallCounter.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/BaseManager.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/GameDTO.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/GameInformable.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/GameManager.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/GameUpdatable.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Inning.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Pitch.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Player.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Score.swift
  iOS/baseball-game/baseball-game/GamePlay/Model/Teams.swift
  iOS/baseball-game/baseball-game/GamePlay/View/AlertFactory.swift
  iOS/baseball-game/baseball-game/GamePlay/View/GamePlay.storyboard
  iOS/baseball-game/baseball-game/GamePlay/ViewModel/GamePlayViewModel.swift
  iOS/baseball-game/baseball-game/Network/Network.swift
  iOS/baseball-game/baseball-game/Selection/Model/DataDTO.swift
  iOS/baseball-game/baseball-game/Selection/SelectionViewController.swift
  iOS/baseball-game/baseball-game/Selection/ViewModel/SelectViewModel.swift
Labels: review-iOS

#42 [FE] [Team 16: coco, Pengdori, Rano] CPR 야구게임 마무리!
  FE/.gitignore
  FE/.prettierrc
  FE/jsconfig.json.bak
  FE/package.json
  FE/public/images/background.jpg
  FE/public/images/background2.jpg
  FE/public/images/github.jpeg
  FE/public/images/라이언.gif
  FE/public/index.html
  FE/src/App.js
  FE/src/common/reference.js
  FE/src/common/style/AppStyle.jsx
  FE/src/common/style/reset.css
  FE/src/common/style/theme.js
  FE/src/common/util.js
  FE/src/components/auth/auth.js
  FE/src/components/auth/login.jsx
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/battleGround/partial/BaseballStadium.jsx
  FE/src/components/gamePlay/battleGround/partial/PitchButton.jsx
  FE/src/components/gamePlay/battleGround/partial/Round.jsx
  FE/src/components/gamePlay/battleGround/partial/SBO.jsx
  FE/src/components/gamePlay/battleGround/partial/StadiumPlayers.jsx
  FE/src/components/gamePlay/gameScore/GameScore.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreen.jsx
  FE/src/components/gamePlay/situationScreen/SituationScreen.jsx
  FE/src/components/gamePlay/situationScreen/situation/Situation.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationRecord.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationStatus.jsx
  FE/src/components/playerListPopup/PlayerListPopup.jsx
  FE/src/components/playerListPopup/partial/ListTable.jsx
  FE/src/components/teamScorePopup/TeamScorePopup.jsx
  FE/src/components/teamScorePopup/partial/ScoreTable.jsx
  FE/src/components/teamScorePopup/partial/Turn.jsx
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/teamSelect/selectTemplate/partial/Desc.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGame.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGameItem.jsx
  FE/src/components/utilComponent/Background.jsx
  FE/src/components/utilComponent/CommonStyledCSS.jsx
  FE/src/components/utilComponent/Logo.jsx
  FE/src/components/utilComponent/MainFrame.jsx
  FE/src/components/utilComponent/context/GamePlayProvider.jsx
  FE/src/components/utilComponent/context/GlobalProvider.jsx
  FE/src/components/utilComponent/modal/Modal.jsx
  FE/src/components/utilComponent/modal/ModalCloseButton.jsx
  FE/src/components/utilComponent/popupFrame/PopupFrame.jsx
  FE/src/components/utilComponent/popupFrame/PopupFrameBackground.jsx
  FE/src/config/authMethods.js
  FE/src/config/firebase-config.js
  FE/src/hooks/useFetch.jsx
  FE/src/index.js
  FE/src/pages/GamePlayPage.jsx
  FE/src/pages/IntroPage.jsx
  FE/src/setupProxy.js.bak
  README.md
Labels: review-FE

#45 [Team-13] 야구게임
  BE/init
  FE/react-baseball/.gitignore
  FE/react-baseball/README.md
  FE/react-baseball/package-lock.json
  FE/react-baseball/package.json
  FE/react-baseball/public/baseballRound.jpg
  FE/react-baseball/public/favicon.ico
  FE/react-baseball/public/games-modi.json
  FE/react-baseball/public/games.json
  FE/react-baseball/public/index.html
  FE/react-baseball/public/players-modi.json
  FE/react-baseball/public/players.json
  FE/react-baseball/src/App.css
  FE/react-baseball/src/App.jsx
  FE/react-baseball/src/components/hooks/useFetch.jsx
  FE/react-baseball/src/components/hooks/useToggle.jsx
  FE/react-baseball/src/components/playScreen/CurrentPlayer.jsx
  FE/react-baseball/src/components/playScreen/LogList.jsx
  FE/react-baseball/src/components/playScreen/PlayInning.jsx
  FE/react-baseball/src/components/playScreen/Score.jsx
  FE/react-baseball/src/components/playScreen/Stadium.jsx
  FE/react-baseball/src/components/provider/Context.jsx
  FE/react-baseball/src/components/reducer/ballReducer.js
  FE/react-baseball/src/components/startScreen/Caption.jsx
  FE/react-baseball/src/components/startScreen/Game.jsx
  FE/react-baseball/src/components/startScreen/GameList.jsx
  FE/react-baseball/src/components/startScreen/Team.jsx
  FE/react-baseball/src/components/startScreen/Title.jsx
  FE/react-baseball/src/index.css
  FE/react-baseball/src/index.js
  FE/react-baseball/src/routes/PlayScreen.jsx
  FE/react-baseball/src/routes/StartScreen.jsx
  FE/react-baseball/src/theme.js
  FE/react-baseball/yarn.lock
Labels: review-FE

#35 [ FE ][Team 15: Yeon, Beemo, Jenny] 야구게임 구현
  FE/client/jsconfig.json
  FE/client/package.json
  FE/client/server/server.js
  FE/client/src/App.js
  FE/client/src/Components/GamePage/GamePageHeader/HeaderLeft/BaseballHeaderScore.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderRight/CurrentPlayer.jsx
  FE/client/src/Components/GamePage/GamePageHeader/HeaderRight/index.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/AttackDefendStatus.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/BaseballField.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/BaseballMonitor.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/PitchButton.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/ReadyImage.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/RunnerImage.jsx
  FE/client/src/Components/GamePage/MainContainer/MainLeft/SBOStatus.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoard.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoardItems.jsx
  FE/client/src/Components/GamePage/MainContainer/MainRight/StatusBoardList.jsx
  FE/client/src/Components/GamePage/Popup/BottomPopup.jsx
  FE/client/src/Components/GamePage/Popup/GameScoreTable.jsx
  FE/client/src/Components/GamePage/Popup/PlayerScoreTable.jsx
  FE/client/src/Components/GamePage/Popup/TopPopup.jsx
  FE/client/src/Components/GamePage/index.jsx
  FE/client/src/Components/Home/GameList/Game.jsx
  FE/client/src/Components/Home/GameList/Team.jsx
  FE/client/src/Components/Home/GameList/index.jsx
  FE/client/src/Components/Home/index.jsx
  FE/client/src/Components/Page/index.jsx
  FE/client/src/index.js
  FE/client/src/utils/API.js
  FE/client/src/utils/BeemoRouter.jsx
  FE/client/src/utils/mockDatas.js
  FE/client/src/utils/randomPitch.js
  README.md
Labels: review-FE

#44 [Team-21, 노을] baseball 기능 구현 및 배포
  be/.gitignore
  be/build.gradle
  be/docs/ERD/ERD.mwb
  be/docs/ERD/ERD.png
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/team22/baseball/BaseballApplication.java
  be/src/main/java/com/team22/baseball/controller/ApiGameController.java
  be/src/main/java/com/team22/baseball/controller/GameExceptionHandler.java
  be/src/main/java/com/team22/baseball/domain/Game.java
  be/src/main/java/com/team22/baseball/domain/Player.java
  be/src/main/java/com/team22/baseball/domain/PlayerHistory.java
  be/src/main/java/com/team22/baseball/domain/Team.java
  be/src/main/java/com/team22/baseball/domain/TeamScore.java
  be/src/main/java/com/team22/baseball/dto/request/SelectTeam.java
  be/src/main/java/com/team22/baseball/dto/request/UpdatePlayerInfo.java
  be/src/main/java/com/team22/baseball/dto/response/ApiResult.java
  be/src/main/java/com/team22/baseball/dto/response/DetailScore/DetailScore.java
  be/src/main/java/com/team22/baseball/dto/response/GameList/GameInfo.java
  be/src/main/java/com/team22/baseball/dto/response/PlayerScoreList/PlayerInfo.java
  be/src/main/java/com/team22/baseball/dto/response/PlayerScoreList/ScoreList.java
  be/src/main/java/com/team22/baseball/dto/response/PlayerScoreList/TeamInfo.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/NextPlayerInfoDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/PlayerInfoDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/TeamInfoDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/TeamListDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/TeamTypeDto.java
  be/src/main/java/com/team22/baseball/exception/NotFoundException.java
  be/src/main/java/com/team22/baseball/repository/GameRepository.java
  be/src/main/java/com/team22/baseball/service/GameService.java
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
  be/src/main/resources/frontBuild.sh
  be/src/main/resources/schema.sql
  be/src/main/resources/serverBuild.sh
  be/src/main/resources/temp.sql
  be/src/test/java/com/team22/baseball/BaseballApplicationTests.java
  be/src/test/java/com/team22/baseball/service/GameServiceTest.java
Labels: review-BE
